name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Установка зависимостей
        run: |
          pip install -r requirements-server.txt -r requirements-client.txt flake8 pytest
      - name: Запуск flake8
        run: flake8 .
      - name: Запуск pytest
        run: pytest
