name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Установка flake8
        run: pip install flake8
      - name: Запуск flake8
        run: flake8 .

  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Установка зависимостей
        run: |
          pip install -r requirements-server.txt pytest
      - name: Запуск тестов сервера
        run: pytest

  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Установка зависимостей
        run: |
          pip install -r requirements-client.txt pytest
      - name: Запуск тестов клиента
        run: pytest client
